# -*- coding: utf-8 -*-
"""520_test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_DIMO39nULbKOlgUECsViUF1X4ZN6shZ
"""

import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import pandas as pd

# load iris dataset
import pandas as pd

import seaborn as sns
df = sns.load_dataset('iris')
df.head

def split_up_interval(minimum, maximum, n_splits=10):
    return minimum + (maximum - minimum) * np.linspace(0,1,n_splits)



import matplotlib
import matplotlib.pyplot as plt # plt is the interface for creating and customizing plots, 
#plt.hist (df["sepal_length"],bins=split_up_interval(1, 10, 1))
plt.hist (df["sepal_length"])
plt.xlabel("Sepal Length")
plt.ylabel("Number of flowers")

import matplotlib
import matplotlib.pyplot as plt # plt is the interface for creating and customizing plots, 
plt.hist (df["sepal_length"],bins=split_up_interval(1, 10, 30))
#plt.hist (df["sepal_length"])
plt.xlabel("Sepal Length")
plt.ylabel("Number of flowers")
#split_up_interval(1, 10, 200)
#plt.hist (df["sepal_length"])
#plt.hist(cardio_df["serum_cholesterol_mg_dl"], bins=split_up_interval(120, 570, 20), cumulative=False)

plt.hist(df["serum_cholesterol_mg_dl"], bins=split_up_interval(120, 570, 100))

split_up_interval(1, 10, 10)



plt.xlabel("Sepal Width")
plt.ylabel("Number of flowers")
plt.hist (df["sepal_width"])

plt.hist (df["sepal_width"],bins=split_up_interval(1, 10, 5))

plt.hist (df["petal_length"])
plt.xlabel("Petal Length")
plt.ylabel("Number of flowers")

plt.hist (df["petal_length"],bins=split_up_interval(1, 10, 30))

plt.hist (df["petal_width"])
plt.xlabel("Petal Width")
plt.ylabel("Number of flowers")
plt.hist (df["petal_width"])

plt.hist (df["sepal_length"],bins=split_up_interval(1, 10, 100))